// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrYTgeYAiHv34rt7Xg1HMy7j8ELuj3Ek4',
    appId: '1:286712669561:web:30a48206c432a3948d3ba8',
    messagingSenderId: '286712669561',
    projectId: 'user-chat-e6722',
    authDomain: 'user-chat-e6722.firebaseapp.com',
    storageBucket: 'user-chat-e6722.appspot.com',
    measurementId: 'G-TPJXCGKGJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_OPR_6vKJwlpvPhceVm6zkfaNjtSTSc',
    appId: '1:286712669561:android:add7dc850dde19928d3ba8',
    messagingSenderId: '286712669561',
    projectId: 'user-chat-e6722',
    storageBucket: 'user-chat-e6722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrTP_5kdD2-cZleHfexCNtKKGwbJoFxg',
    appId: '1:286712669561:ios:6b7e2eb2ffedde388d3ba8',
    messagingSenderId: '286712669561',
    projectId: 'user-chat-e6722',
    storageBucket: 'user-chat-e6722.appspot.com',
    iosBundleId: 'com.example.userChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnrTP_5kdD2-cZleHfexCNtKKGwbJoFxg',
    appId: '1:286712669561:ios:7c3ad04471ac7df38d3ba8',
    messagingSenderId: '286712669561',
    projectId: 'user-chat-e6722',
    storageBucket: 'user-chat-e6722.appspot.com',
    iosBundleId: 'com.example.userChat.RunnerTests',
  );
}
